import { agentSessionsEndpoints } from './agent-sessions/api.js';
import { clientSettingsEndpoint } from './client-settings/api.js';
import { commandsEndpoints } from './commands/api.js';
import { controlPlaneEndpoints } from './control-plane/api.js';
import { healthEndpoint } from './health/api.js';
import { pathsEndpoints } from './paths/api.js';
import { projectsEndpoints } from './projects/api.js';
import { runtimeEventsWebSocketEndpoint } from './runtime-events/api.js';
import { surfacesEndpoints } from './surfaces/api.js';
import { workflowsEndpoints } from './workflows/api.js';
import { workspaceEndpoints } from './workspace/api.js';
import { worktreesEndpoints } from './worktrees/api.js';

export const apiEndpoints = {
  agentSessions: agentSessionsEndpoints,
  commands: commandsEndpoints,
  clientSettings: clientSettingsEndpoint,
  controlPlane: controlPlaneEndpoints,
  health: healthEndpoint,
  workspace: workspaceEndpoints,
  projects: projectsEndpoints,
  runtimeEvents: runtimeEventsWebSocketEndpoint,
  worktrees: worktreesEndpoints,
  surfaces: surfacesEndpoints,
  workflows: workflowsEndpoints,
  paths: pathsEndpoints,
} as const;

export {
  agentSessionActivityApiErrorSchema,
  agentSessionActivityUnavailableErrorSchema,
  agentSessionsEndpoints,
} from './agent-sessions/api.js';
export { agentSessionActivityOutputSchema } from './agent-sessions/types.js';
export type { AgentSessionActivityOutput } from './agent-sessions/types.js';

export { clientSettingsEndpoint } from './client-settings/api.js';
export {
  clientSettingsOutputSchema,
  terminalCacheSettingsSchema,
  terminalSettingsBounds,
  terminalSettingsDefaults,
  terminalSettingsSchema,
} from './client-settings/types.js';
export type {
  ClientSettingsOutput,
  TerminalCacheSettings,
  TerminalSettings,
} from './client-settings/types.js';

export { controlPlaneEndpoints, controlPlaneErrorSchema } from './control-plane/api.js';
export * from './control-plane/types.js';

export {
  apiBaseErrorResponseSchema,
  apiBasePath,
  apiErrorBaseSchema,
  apiErrorResponseSchema,
  apiInfrastructureErrorCodeSchema,
  apiInfrastructureErrorSchema,
  apiSuccessResponseSchema,
  responseMetaSchema,
} from './api/responses.js';

export {
  DESKTOP_UPDATE_PROTOCOL_VERSION,
  desktopUpdateFailureCodeSchema,
  desktopUpdateIntentSchema,
  desktopUpdateSnapshotSchema,
} from './desktop-update/types.js';
export type {
  DesktopUpdateFailureCode,
  DesktopUpdateIntent,
  DesktopUpdateSnapshot,
} from './desktop-update/types.js';
export type {
  ApiError,
  ApiErrorResponse,
  ApiInfrastructureError,
  ApiInfrastructureErrorCode,
  ApiSuccessResponse,
  ResponseMeta,
} from './api/responses.js';

export type {
  ApiEndpoint,
  ApiEndpointBody,
  ApiEndpointError,
  ApiEndpointOutput,
  ApiEndpointParams,
  ApiEndpointQuery,
  ApiEndpointRequestArgs,
  ApiMethod,
} from './api/types.js';

export { HOST_RUNTIME_STATUS_PROTOCOL_VERSION } from './host-runtime/types.js';
export type {
  HostRuntimeDiagnostic,
  HostRuntimeFailureReason,
  HostRuntimeOwnership,
  HostRuntimeStatusSnapshot,
} from './host-runtime/types.js';

export {
  gitCommandFailedErrorSchema,
  projectApiErrorSchema,
  projectDeleteApiErrorSchema,
  projectDeleteRejectedErrorSchema,
  projectDeleteRejectionReasonSchema,
  projectOperationRejectedErrorSchema,
  projectOperationRejectionReasonSchema,
  projectOrderApiErrorSchema,
  projectOrderRejectedErrorSchema,
  projectOrderRejectionReasonSchema,
  projectPathRejectedErrorSchema,
  projectPathRejectionReasonSchema,
  projectRelocateApiErrorSchema,
  projectRelocationRejectedErrorSchema,
  projectRelocationRejectionReasonSchema,
  runtimeDataDirectoryFailedErrorSchema,
  runtimeDatabaseFailedErrorSchema,
  runtimeStateFileFailedErrorSchema,
  sessionLaunchApiErrorSchema,
  sessionLaunchRejectedErrorSchema,
  sessionLaunchRejectionReasonSchema,
  surfaceApiErrorSchema,
  surfaceOrderApiErrorSchema,
  surfaceOrderRejectedErrorSchema,
  surfaceOrderRejectionReasonSchema,
  surfaceRejectedErrorSchema,
  surfaceRejectionReasonSchema,
  workspaceActiveContextApiErrorSchema,
  workspaceActiveContextRejectedErrorSchema,
  workspaceActiveContextRejectionReasonSchema,
  workspaceGetApiErrorSchema,
  workspaceReconcileApiErrorSchema,
  workspaceReconcileRejectedErrorSchema,
  workspaceReconcileRejectionReasonSchema,
  worktreeEnvironmentFocusApiErrorSchema,
  worktreeEnvironmentFocusRejectedErrorSchema,
  worktreeEnvironmentFocusRejectionReasonSchema,
  worktreeBranchListApiErrorSchema,
  worktreeBranchListRejectedErrorSchema,
  worktreeCommandsApiErrorSchema,
  worktreeCommandsRejectedErrorSchema,
  worktreeCommandsRejectionReasonSchema,
  workflowApiErrorSchema,
  workflowRejectedErrorSchema,
  workflowRejectionReasonSchema,
  worktreeDeleteApiErrorSchema,
  worktreeDeleteRejectedErrorSchema,
  worktreeDeleteRejectionReasonSchema,
  worktreeOpenApiErrorSchema,
  worktreeOpenRejectedErrorSchema,
  worktreeOperationRejectionReasonSchema,
  worktreeOrderApiErrorSchema,
  worktreeOrderRejectedErrorSchema,
  worktreeOrderRejectionReasonSchema,
  worktreeSetupApiErrorSchema,
  worktreeSetupRejectedErrorSchema,
  worktreeSetupRejectionReasonSchema,
} from './api/errors.js';
export type {
  ProjectPathRejectedError,
  ProjectPathRejectionReason,
  ProjectDeleteRejectedError,
  ProjectDeleteRejectionReason,
  ProjectOperationRejectedError,
  ProjectOperationRejectionReason,
  ProjectOrderRejectedError,
  ProjectOrderRejectionReason,
  ProjectRelocationRejectedError,
  ProjectRelocationRejectionReason,
  SessionLaunchRejectedError,
  SessionLaunchRejectionReason,
  SurfaceOrderRejectedError,
  SurfaceOrderRejectionReason,
  SurfaceRejectedError,
  SurfaceRejectionReason,
  WorktreeCommandsRejectedError,
  WorktreeCommandsRejectionReason,
  WorkflowRejectionReason,
  WorkspaceActiveContextRejectedError,
  WorkspaceActiveContextRejectionReason,
  WorkspaceReconcileRejectedError,
  WorkspaceReconcileRejectionReason,
  WorktreeEnvironmentFocusRejectedError,
  WorktreeEnvironmentFocusRejectionReason,
  WorktreeBranchListRejectedError,
  WorktreeDeleteRejectedError,
  WorktreeDeleteRejectionReason,
  WorktreeOpenRejectedError,
  WorktreeOperationRejectionReason,
  WorktreeOrderRejectedError,
  WorktreeOrderRejectionReason,
  WorktreeSetupRejectedError,
  WorktreeSetupRejectionReason,
} from './api/errors.js';

export { commandLogStreamWebSocketEndpoint, commandsEndpoints } from './commands/api.js';
export {
  commandConfigDiagnosticSchema,
  commandActionOutputSchema,
  commandLogMetadataLatestRunSchema,
  commandLogMetadataOutputSchema,
  commandLogStreamErrorCodeSchema,
  commandLogStreamErrorMessageSchema,
  commandLogStreamOutputMessageSchema,
  commandLogStreamStateMessageSchema,
  commandPortSchema,
  commandPortUrlSchema,
  commandRunDiagnosticReasonSchema,
  commandRunDiagnosticSchema,
  commandRunStatusSchema,
  commandStatusSchema,
  commandSummarySchema,
  worktreeCommandActionInputSchema,
  worktreeCommandQuerySchema,
  worktreeCommandsOutputSchema,
  worktreeCommandsRouteParamsSchema,
} from './commands/types.js';
export type {
  CommandActionOutput,
  CommandConfigDiagnostic,
  CommandLogMetadataLatestRun,
  CommandLogMetadataOutput,
  CommandLogStreamErrorCode,
  CommandLogStreamOutputMessage,
  CommandLogStreamStateMessage,
  CommandPort,
  CommandPortUrl,
  CommandRunDiagnostic,
  CommandRunDiagnosticReason,
  CommandRunStatus,
  CommandStatus,
  CommandSummary,
  WorktreeCommandActionInput,
  WorktreeCommandQuery,
  WorktreeCommandsOutput,
  WorktreeCommandsRouteParams,
} from './commands/types.js';

export { healthEndpoint } from './health/api.js';
export { healthOutputSchema } from './health/types.js';
export type { HealthOutput } from './health/types.js';

export {
  advanceWorkflowInputSchema,
  getWorkflowRunOutputSchema,
  listWorkflowDescriptorsInputSchema,
  listWorkflowDescriptorsOutputSchema,
  listWorkflowRunsOutputSchema,
  listWorkflowRunsQuerySchema,
  startWorkflowInputSchema,
  startWorkflowOutputSchema,
  workflowEventsQuerySchema,
  workflowCommandManifestSchema,
  workflowBlockingWaitSchema,
  workflowDescriptorResultSchema,
  workflowEventAppendedMessageSchema,
  workflowEventSchema,
  workflowEventsReplayOutputSchema,
  workflowEventsRequestedMessageSchema,
  workflowEventsSnapshotMessageSchema,
  workflowEventsStreamErrorCodeSchema,
  workflowEventsStreamErrorMessageSchema,
  workflowEventsStreamInputMessageSchema,
  workflowEventsStreamOutputMessageSchema,
  workflowLifecycleEventEnvelopeSchema,
  workflowLifecycleEventSchema,
  workflowLogEventSchema,
  workflowLogLevelSchema,
  workflowRunControlOutputSchema,
  workflowRunRouteParamsSchema,
  workflowRunStatusSchema,
  workflowLoadFailureReasonSchema,
  workflowRunSummarySchema,
  workflowInputKindSchema,
  workflowQuestionOptionSchema,
  workflowQuestionSpecSchema,
  workflowStartContextSchema,
  workflowUiFeedbackSchema,
  workflowWaitKindSchema,
} from './workflows/types.js';
export type {
  AdvanceWorkflowInput,
  GetWorkflowRunOutput,
  ListWorkflowDescriptorsInput,
  ListWorkflowDescriptorsOutput,
  ListWorkflowRunsOutput,
  ListWorkflowRunsQuery,
  StartWorkflowInput,
  StartWorkflowOutput,
  WorkflowBlockingWait,
  WorkflowCommandManifestDto,
  WorkflowDescriptorResult,
  WorkflowEvent,
  WorkflowEventsReplayOutput,
  WorkflowEventsStreamErrorCode,
  WorkflowEventsStreamInputMessage,
  WorkflowEventsStreamOutputMessage,
  WorkflowInputKind,
  WorkflowLifecycleEvent,
  WorkflowLogLevelDto,
  WorkflowQuestionOptionDto,
  WorkflowQuestionSpecDto,
  WorkflowRunControlOutput,
  WorkflowRunRouteParams,
  WorkflowRunStatus,
  WorkflowLoadFailureReason,
  WorkflowRunSummary,
  WorkflowEventsQuery,
  WorkflowStartContext,
  WorkflowUiFeedbackDto,
} from './workflows/types.js';
export { workflowEventsStreamWebSocketEndpoint, workflowsEndpoints } from './workflows/api.js';

export { pathsEndpoints } from './paths/api.js';
export {
  pathSuggestInputSchema,
  pathSuggestOutputSchema,
  pathSuggestionSchema,
} from './paths/types.js';
export type { PathSuggestInput, PathSuggestOutput, PathSuggestion } from './paths/types.js';

export {
  ptyStreamErrorCodeSchema,
  ptyStreamErrorMessageSchema,
  ptyStreamKnownErrorCodeSchema,
  ptyStreamExitMessageSchema,
  ptyStreamOutputMessageSchema,
  ptyStreamOutputMessageSetSchema,
  ptyStreamReplayEndMessageSchema,
  ptyStreamReplayStartMessageSchema,
  ptyStreamTransportErrorCodeSchema,
} from './pty-stream/types.js';
export type {
  PtyStreamErrorCode,
  PtyStreamErrorMessage,
  PtyStreamExitMessage,
  PtyStreamOutputMessage,
  PtyStreamOutputMessageSet,
  PtyStreamReplayEndMessage,
  PtyStreamReplayStartMessage,
} from './pty-stream/types.js';

export { projectsEndpoints } from './projects/api.js';
export {
  addProjectInputSchema,
  addProjectOutputSchema,
  deleteProjectOutputSchema,
  moveProjectOrderInputSchema,
  moveProjectOrderOutputSchema,
  projectRouteParamsSchema,
  relocateProjectInputSchema,
  relocateProjectOutputSchema,
} from './projects/types.js';
export type {
  AddProjectInput,
  AddProjectOutput,
  DeleteProjectOutput,
  MoveProjectOrderInput,
  MoveProjectOrderOutput,
  ProjectRouteParams,
  RelocateProjectInput,
  RelocateProjectOutput,
} from './projects/types.js';
export { runtimeEventsWebSocketEndpoint } from './runtime-events/api.js';
export {
  attentionSnapshotEventSchema,
  attentionSourceChangedEventSchema,
  attentionSourceIdentitySchema,
  attentionSourceRemovedEventSchema,
  attentionSourceSchema,
  attentionStateSchema,
  commandChangedEventSchema,
  durableSessionDeletedEventSchema,
  workflowRunChangedEventSchema,
  workflowRunClearedEventSchema,
  workflowRunSnapshotEventSchema,
  terminalAttentionStateSchema,
  agentSessionChangedEventSchema,
  runtimeEventBaseSchema,
  runtimeEventInputMessageSchema,
  runtimeEventInputTypeSchema,
  runtimeEventSchema,
  runtimeEventTypeSchema,
  surfaceChangedEventSchema,
  terminalSessionChangedEventSchema,
} from './runtime-events/types.js';
export type {
  AgentSessionChangedEvent,
  CommandChangedEvent,
  AttentionSnapshotEvent,
  AttentionSource,
  AttentionSourceChangedEvent,
  AttentionSourceIdentity,
  AttentionSourceRemovedEvent,
  AttentionState,
  DurableSessionDeletedEvent,
  TerminalAttentionState,
  RuntimeEvent,
  RuntimeEventBase,
  RuntimeEventInputMessage,
  RuntimeEventInputType,
  RuntimeEventType,
  SurfaceChangedEvent,
  TerminalSessionChangedEvent,
  WorkflowRunChangedEvent,
  WorkflowRunClearedEvent,
  WorkflowRunSnapshotEvent,
} from './runtime-events/types.js';
export {
  agentSessionPtyWebSocketEndpoint,
  surfacesEndpoints,
  terminalSessionPtyWebSocketEndpoint,
} from './surfaces/api.js';
export {
  agentHarnessSchema,
  agentSessionMetadataSchema,
  agentSessionRecoveryActionSchema,
  agentSessionRouteParamsSchema,
  agentSessionStatusReasonSchema,
  createSurfaceInputSchema,
  createSurfaceOutputSchema,
  deleteSurfaceOutputSchema,
  harnessLaunchBlockReasonSchema,
  moveSurfaceOrderInputSchema,
  moveSurfaceOrderOutputSchema,
  paneSessionKindSchema,
  paneSessionClaimInputSchema,
  paneSessionClaimOutputSchema,
  paneSessionCreateInputSchema,
  paneSessionSpecSchema,
  ptyProcessBackendSchema,
  ptyProcessLogModeSchema,
  ptyWebSocketErrorCodeSchema,
  ptyWebSocketErrorMessageSchema,
  ptyWebSocketInputMessageSchema,
  ptyWebSocketOutputMessageSchema,
  renameSurfaceInputSchema,
  renameSurfaceOutputSchema,
  sessionDiagnosticCodeSchema,
  sessionStatusSchema,
  setSplitWeightsInputSchema,
  setSplitWeightsOutputSchema,
  setWorktreeEnvironmentFocusInputSchema,
  splitPaneDirectionSchema,
  splitPaneInputSchema,
  surfaceDetailSchema,
  surfaceLayoutAxisSchema,
  surfaceLayoutNodeSchema,
  surfaceLayoutSizingSchema,
  surfacePaneSchema,
  surfacePaneSessionSchema,
  surfacePaneRouteParamsSchema,
  surfaceRouteParamsSchema,
  terminalSessionMetadataSchema,
  terminalSessionRouteParamsSchema,
  terminalSessionStatusReasonSchema,
  worktreeEnvironmentFocusOutputSchema,
  worktreeEnvironmentFocusRouteParamsSchema,
  worktreeSurfaceRouteParamsSchema,
} from './surfaces/types.js';
export type {
  AgentHarness,
  AgentSessionMetadata,
  AgentSessionRecoveryAction,
  AgentSessionRouteParams,
  AgentSessionStatusReason,
  CreateSurfaceInput,
  CreateSurfaceOutput,
  DeleteSurfaceOutput,
  HarnessLaunchBlockReason,
  PaneSessionKind,
  PaneSessionClaimInput,
  PaneSessionClaimOutput,
  PaneSessionCreateInput,
  PaneSessionSpec,
  PtyProcessBackend,
  PtyProcessLogMode,
  PtyWebSocketErrorCode,
  PtyWebSocketInputMessage,
  PtyWebSocketOutputMessage,
  RenameSurfaceInput,
  RenameSurfaceOutput,
  SessionDiagnosticCode,
  SessionStatus,
  SetSplitWeightsInput,
  SetSplitWeightsOutput,
  SetWorktreeEnvironmentFocusInput,
  SplitPaneDirection,
  SplitPaneInput,
  SurfaceDetail,
  SurfaceLayoutLeaf,
  SurfaceLayoutNode,
  SurfaceLayoutSplit,
  SurfacePane,
  SurfacePaneRouteParams,
  SurfacePaneSession,
  SurfaceRouteParams,
  TerminalSessionMetadata,
  TerminalSessionRouteParams,
  TerminalSessionStatusReason,
  MoveSurfaceOrderInput,
  MoveSurfaceOrderOutput,
  WorktreeEnvironmentFocusOutput,
  WorktreeEnvironmentFocusRouteParams,
  WorktreeSurfaceRouteParams,
} from './surfaces/types.js';
export { workspaceEndpoints } from './workspace/api.js';
export {
  activeContextOutputSchema,
  activeContextPersistenceInputSchema,
  activeContextSchema,
  projectSchema,
  projectStatusSchema,
  reconcileWorkspaceInputSchema,
  reconcileWorkspaceOutputSchema,
  reconciliationFindingSchema,
  setActiveContextInputSchema,
  surfaceSchema,
  workspaceSnapshotSchema,
  durableSessionIdentitySchema,
  durableSessionInventorySchema,
  worktreeSchema,
} from './workspace/types.js';
export type {
  ActiveContext,
  ActiveContextOutput,
  ActiveContextPersistenceInput,
  Project,
  ProjectStatus,
  ReconcileWorkspaceInput,
  ReconcileWorkspaceOutput,
  ReconciliationFinding,
  SetActiveContextInput,
  SetActiveContextOutput,
  WorkspaceSurfaceMetadata,
  WorkspaceSnapshot,
  DurableSessionIdentity,
  DurableSessionInventory,
  Worktree,
} from './workspace/types.js';

export { worktreesEndpoints } from './worktrees/api.js';
export {
  branchRemovalModeSchema,
  checkoutRemovalModeSchema,
  deleteWorktreeInputSchema,
  deleteWorktreeOutputSchema,
  deleteWorktreePreflightOutputSchema,
  listProjectBranchesOutputSchema,
  moveWorktreeOrderInputSchema,
  moveWorktreeOrderOutputSchema,
  openWorktreeInputSchema,
  openWorktreeOutputSchema,
  openWorktreeStatusSchema,
  projectWorktreeRouteParamsSchema,
  worktreeBranchRemovalSchema,
  worktreeBaseRefSchema,
  worktreeBranchSchema,
  worktreeRouteParamsSchema,
  worktreeSetupHookTypeSchema,
  worktreeSetupLifecycleSchema,
  worktreeSetupPreflightOutputSchema,
  worktreeSetupPreflightStatusSchema,
  worktreeSetupResultSchema,
  worktreeSetupSummarySchema,
  worktreeSetupTrustInputSchema,
  worktreeSetupTrustOutputSchema,
} from './worktrees/types.js';
export type {
  BranchRemovalMode,
  CheckoutRemovalMode,
  DeleteWorktreeInput,
  DeleteWorktreeOutput,
  DeleteWorktreePreflightOutput,
  ListProjectBranchesOutput,
  MoveWorktreeOrderInput,
  MoveWorktreeOrderOutput,
  OpenWorktreeInput,
  OpenWorktreeOutput,
  OpenWorktreeStatus,
  ProjectWorktreeRouteParams,
  WorktreeBranchRemoval,
  WorktreeBaseRef,
  WorktreeBranch,
  WorktreeRouteParams,
  WorktreeSetupHookType,
  WorktreeSetupLifecycle,
  WorktreeSetupPreflightOutput,
  WorktreeSetupPreflightStatus,
  WorktreeSetupResult,
  WorktreeSetupSummary,
  WorktreeSetupTrustInput,
  WorktreeSetupTrustOutput,
} from './worktrees/types.js';
