import { commandsEndpoints } from './commands/api.js';
import { healthEndpoint } from './health/api.js';
import { pathsEndpoints } from './paths/api.js';
import { projectsEndpoints } from './projects/api.js';
import { runtimeEventsWebSocketEndpoint } from './runtime-events/api.js';
import { surfacesEndpoints } from './surfaces/api.js';
import { workspaceEndpoints } from './workspace/api.js';
import { worktreesEndpoints } from './worktrees/api.js';

export const apiEndpoints = {
  commands: commandsEndpoints,
  health: healthEndpoint,
  workspace: workspaceEndpoints,
  projects: projectsEndpoints,
  runtimeEvents: runtimeEventsWebSocketEndpoint,
  worktrees: worktreesEndpoints,
  surfaces: surfacesEndpoints,
  paths: pathsEndpoints,
} as const;

export {
  apiBaseErrorResponseSchema,
  apiBasePath,
  apiErrorBaseSchema,
  apiErrorResponseSchema,
  apiInfrastructureErrorCodeSchema,
  apiInfrastructureErrorSchema,
  apiSuccessResponseSchema,
  responseMetaSchema,
} from './api/responses.js';
export type {
  ApiError,
  ApiErrorResponse,
  ApiInfrastructureError,
  ApiInfrastructureErrorCode,
  ApiSuccessResponse,
  ResponseMeta,
} from './api/responses.js';

export type {
  ApiEndpoint,
  ApiEndpointBody,
  ApiEndpointError,
  ApiEndpointOutput,
  ApiEndpointParams,
  ApiEndpointQuery,
  ApiEndpointRequestArgs,
  ApiMethod,
} from './api/types.js';

export {
  gitCommandFailedErrorSchema,
  projectApiErrorSchema,
  projectDeleteApiErrorSchema,
  projectDeleteRejectedErrorSchema,
  projectDeleteRejectionReasonSchema,
  projectOperationRejectedErrorSchema,
  projectOperationRejectionReasonSchema,
  projectPathRejectedErrorSchema,
  projectPathRejectionReasonSchema,
  projectRelocateApiErrorSchema,
  projectRelocationRejectedErrorSchema,
  projectRelocationRejectionReasonSchema,
  runtimeDataDirectoryFailedErrorSchema,
  runtimeDatabaseFailedErrorSchema,
  runtimeStateFileFailedErrorSchema,
  sessionLaunchApiErrorSchema,
  sessionLaunchRejectedErrorSchema,
  sessionLaunchRejectionReasonSchema,
  surfaceApiErrorSchema,
  surfaceRejectedErrorSchema,
  surfaceRejectionReasonSchema,
  workspaceActiveContextApiErrorSchema,
  workspaceActiveContextRejectedErrorSchema,
  workspaceActiveContextRejectionReasonSchema,
  workspaceGetApiErrorSchema,
  workspaceReconcileApiErrorSchema,
  workspaceReconcileRejectedErrorSchema,
  workspaceReconcileRejectionReasonSchema,
  worktreeEnvironmentFocusApiErrorSchema,
  worktreeEnvironmentFocusRejectedErrorSchema,
  worktreeEnvironmentFocusRejectionReasonSchema,
  worktreeBranchListApiErrorSchema,
  worktreeBranchListRejectedErrorSchema,
  worktreeCommandsApiErrorSchema,
  worktreeCommandsRejectedErrorSchema,
  worktreeCommandsRejectionReasonSchema,
  worktreeDeleteApiErrorSchema,
  worktreeDeleteRejectedErrorSchema,
  worktreeDeleteRejectionReasonSchema,
  worktreeOpenApiErrorSchema,
  worktreeOpenRejectedErrorSchema,
  worktreeOperationRejectionReasonSchema,
  worktreeSetupApiErrorSchema,
  worktreeSetupRejectedErrorSchema,
  worktreeSetupRejectionReasonSchema,
} from './api/errors.js';
export type {
  ProjectPathRejectedError,
  ProjectPathRejectionReason,
  ProjectDeleteRejectedError,
  ProjectDeleteRejectionReason,
  ProjectOperationRejectedError,
  ProjectOperationRejectionReason,
  ProjectRelocationRejectedError,
  ProjectRelocationRejectionReason,
  SessionLaunchRejectedError,
  SessionLaunchRejectionReason,
  SurfaceRejectedError,
  SurfaceRejectionReason,
  WorktreeCommandsRejectedError,
  WorktreeCommandsRejectionReason,
  WorkspaceActiveContextRejectedError,
  WorkspaceActiveContextRejectionReason,
  WorkspaceReconcileRejectedError,
  WorkspaceReconcileRejectionReason,
  WorktreeEnvironmentFocusRejectedError,
  WorktreeEnvironmentFocusRejectionReason,
  WorktreeBranchListRejectedError,
  WorktreeDeleteRejectedError,
  WorktreeDeleteRejectionReason,
  WorktreeOpenRejectedError,
  WorktreeOperationRejectionReason,
  WorktreeSetupRejectedError,
  WorktreeSetupRejectionReason,
} from './api/errors.js';

export { commandLogStreamWebSocketEndpoint, commandsEndpoints } from './commands/api.js';
export {
  commandConfigDiagnosticSchema,
  commandActionOutputSchema,
  commandLogMetadataLatestRunSchema,
  commandLogMetadataOutputSchema,
  commandLogStreamErrorCodeSchema,
  commandLogStreamErrorMessageSchema,
  commandLogStreamOutputMessageSchema,
  commandLogStreamStateMessageSchema,
  commandRunDiagnosticReasonSchema,
  commandRunDiagnosticSchema,
  commandStatusSchema,
  commandSummarySchema,
  worktreeCommandActionInputSchema,
  worktreeCommandQuerySchema,
  worktreeCommandsOutputSchema,
  worktreeCommandsRouteParamsSchema,
} from './commands/types.js';
export type {
  CommandActionOutput,
  CommandConfigDiagnostic,
  CommandLogMetadataLatestRun,
  CommandLogMetadataOutput,
  CommandLogStreamErrorCode,
  CommandLogStreamOutputMessage,
  CommandLogStreamStateMessage,
  CommandRunDiagnostic,
  CommandRunDiagnosticReason,
  CommandStatus,
  CommandSummary,
  WorktreeCommandActionInput,
  WorktreeCommandQuery,
  WorktreeCommandsOutput,
  WorktreeCommandsRouteParams,
} from './commands/types.js';

export { healthEndpoint } from './health/api.js';
export { healthOutputSchema } from './health/types.js';
export type { HealthOutput } from './health/types.js';

export { pathsEndpoints } from './paths/api.js';
export {
  pathSuggestInputSchema,
  pathSuggestOutputSchema,
  pathSuggestionSchema,
} from './paths/types.js';
export type { PathSuggestInput, PathSuggestOutput, PathSuggestion } from './paths/types.js';

export {
  ptyStreamErrorCodeSchema,
  ptyStreamErrorMessageSchema,
  ptyStreamExitMessageSchema,
  ptyStreamOutputMessageSchema,
  ptyStreamOutputMessageSetSchema,
  ptyStreamReplayEndMessageSchema,
  ptyStreamReplayStartMessageSchema,
} from './pty-stream/types.js';
export type {
  PtyStreamErrorCode,
  PtyStreamErrorMessage,
  PtyStreamExitMessage,
  PtyStreamOutputMessage,
  PtyStreamOutputMessageSet,
  PtyStreamReplayEndMessage,
  PtyStreamReplayStartMessage,
} from './pty-stream/types.js';

export { projectsEndpoints } from './projects/api.js';
export {
  addProjectInputSchema,
  addProjectOutputSchema,
  deleteProjectOutputSchema,
  projectRouteParamsSchema,
  relocateProjectInputSchema,
  relocateProjectOutputSchema,
} from './projects/types.js';
export type {
  AddProjectInput,
  AddProjectOutput,
  DeleteProjectOutput,
  ProjectRouteParams,
  RelocateProjectInput,
  RelocateProjectOutput,
} from './projects/types.js';
export { runtimeEventsWebSocketEndpoint } from './runtime-events/api.js';
export {
  attentionSnapshotEventSchema,
  attentionSourceChangedEventSchema,
  attentionSourceIdentitySchema,
  attentionSourceRemovedEventSchema,
  attentionSourceSchema,
  attentionStateSchema,
  commandChangedEventSchema,
  terminalAttentionStateSchema,
  agentSessionChangedEventSchema,
  runtimeEventBaseSchema,
  runtimeEventInputMessageSchema,
  runtimeEventInputTypeSchema,
  runtimeEventSchema,
  runtimeEventTypeSchema,
  terminalSessionChangedEventSchema,
} from './runtime-events/types.js';
export type {
  AgentSessionChangedEvent,
  CommandChangedEvent,
  AttentionSnapshotEvent,
  AttentionSource,
  AttentionSourceChangedEvent,
  AttentionSourceIdentity,
  AttentionSourceRemovedEvent,
  AttentionState,
  TerminalAttentionState,
  RuntimeEvent,
  RuntimeEventBase,
  RuntimeEventInputMessage,
  RuntimeEventInputType,
  RuntimeEventType,
  TerminalSessionChangedEvent,
} from './runtime-events/types.js';
export {
  agentSessionPtyWebSocketEndpoint,
  surfacesEndpoints,
  terminalSessionPtyWebSocketEndpoint,
} from './surfaces/api.js';
export {
  agentHarnessSchema,
  agentSessionMetadataSchema,
  agentSessionRecoveryActionSchema,
  agentSessionRouteParamsSchema,
  agentSessionStatusReasonSchema,
  createSurfaceInputSchema,
  createSurfaceOutputSchema,
  deleteSurfaceOutputSchema,
  launchAgentSurfaceInputSchema,
  paneSessionClaimInputSchema,
  paneSessionClaimOutputSchema,
  paneSessionCreateInputSchema,
  ptyProcessBackendSchema,
  ptyProcessLogModeSchema,
  ptyWebSocketErrorCodeSchema,
  ptyWebSocketInputMessageSchema,
  ptyWebSocketOutputMessageSchema,
  renameSurfaceInputSchema,
  renameSurfaceOutputSchema,
  runtimeSurfaceKindSchema,
  sessionDiagnosticCodeSchema,
  sessionStatusSchema,
  setWorktreeEnvironmentFocusInputSchema,
  surfaceDetailSchema,
  surfaceLayoutAxisSchema,
  surfaceLayoutNodeSchema,
  surfaceLayoutSizingSchema,
  surfacePaneSchema,
  surfacePaneSessionSchema,
  surfacePaneRouteParamsSchema,
  surfaceRouteParamsSchema,
  terminalSessionMetadataSchema,
  terminalSessionRouteParamsSchema,
  terminalSessionStatusReasonSchema,
  worktreeEnvironmentFocusOutputSchema,
  worktreeEnvironmentFocusRouteParamsSchema,
} from './surfaces/types.js';
export type {
  AgentHarness,
  AgentSessionMetadata,
  AgentSessionRecoveryAction,
  AgentSessionRouteParams,
  AgentSessionStatusReason,
  CreateSurfaceInput,
  CreateSurfaceOutput,
  DeleteSurfaceOutput,
  LaunchAgentSurfaceInput,
  PaneSessionClaimInput,
  PaneSessionClaimOutput,
  PaneSessionCreateInput,
  PtyProcessBackend,
  PtyProcessLogMode,
  PtyWebSocketErrorCode,
  PtyWebSocketInputMessage,
  PtyWebSocketOutputMessage,
  RenameSurfaceInput,
  RenameSurfaceOutput,
  RuntimeSurfaceKind,
  SessionDiagnosticCode,
  SessionStatus,
  SetWorktreeEnvironmentFocusInput,
  SurfaceDetail,
  SurfaceLayoutLeaf,
  SurfaceLayoutNode,
  SurfaceLayoutSplit,
  SurfacePane,
  SurfacePaneRouteParams,
  SurfacePaneSession,
  SurfaceRouteParams,
  TerminalSessionMetadata,
  TerminalSessionRouteParams,
  TerminalSessionStatusReason,
  WorktreeEnvironmentFocusOutput,
  WorktreeEnvironmentFocusRouteParams,
} from './surfaces/types.js';
export { workspaceEndpoints } from './workspace/api.js';
export {
  activeContextOutputSchema,
  activeContextPersistenceInputSchema,
  activeContextSchema,
  projectSchema,
  projectStatusSchema,
  reconcileWorkspaceInputSchema,
  reconcileWorkspaceOutputSchema,
  reconciliationFindingSchema,
  setActiveContextInputSchema,
  surfaceSchema,
  workspaceSnapshotSchema,
  worktreeSchema,
} from './workspace/types.js';
export type {
  ActiveContext,
  ActiveContextOutput,
  ActiveContextPersistenceInput,
  Project,
  ProjectStatus,
  ReconcileWorkspaceInput,
  ReconcileWorkspaceOutput,
  ReconciliationFinding,
  SetActiveContextInput,
  SetActiveContextOutput,
  WorkspaceSurfaceMetadata,
  WorkspaceSnapshot,
  Worktree,
} from './workspace/types.js';

export { worktreesEndpoints } from './worktrees/api.js';
export {
  branchRemovalModeSchema,
  checkoutRemovalModeSchema,
  deleteWorktreeInputSchema,
  deleteWorktreeOutputSchema,
  deleteWorktreePreflightOutputSchema,
  listProjectBranchesOutputSchema,
  openWorktreeInputSchema,
  openWorktreeOutputSchema,
  openWorktreeStatusSchema,
  projectWorktreeRouteParamsSchema,
  worktreeBranchRemovalSchema,
  worktreeBaseRefSchema,
  worktreeBranchSchema,
  worktreeRouteParamsSchema,
  worktreeSetupHookTypeSchema,
  worktreeSetupLifecycleSchema,
  worktreeSetupPreflightOutputSchema,
  worktreeSetupPreflightStatusSchema,
  worktreeSetupResultSchema,
  worktreeSetupSummarySchema,
  worktreeSetupTrustInputSchema,
  worktreeSetupTrustOutputSchema,
} from './worktrees/types.js';
export type {
  BranchRemovalMode,
  CheckoutRemovalMode,
  DeleteWorktreeInput,
  DeleteWorktreeOutput,
  DeleteWorktreePreflightOutput,
  ListProjectBranchesOutput,
  OpenWorktreeInput,
  OpenWorktreeOutput,
  OpenWorktreeStatus,
  ProjectWorktreeRouteParams,
  WorktreeBranchRemoval,
  WorktreeBaseRef,
  WorktreeBranch,
  WorktreeRouteParams,
  WorktreeSetupHookType,
  WorktreeSetupLifecycle,
  WorktreeSetupPreflightOutput,
  WorktreeSetupPreflightStatus,
  WorktreeSetupResult,
  WorktreeSetupSummary,
  WorktreeSetupTrustInput,
  WorktreeSetupTrustOutput,
} from './worktrees/types.js';
