import { workflowApiErrorSchema } from '../api/errors.js';
import type { ApiContentEndpoint, ApiEndpoint } from '../api/types.js';
import {
  advanceWorkflowInputSchema,
  getWorkflowAttemptOutputSchema,
  getWorkflowCheckpointOutputSchema,
  getWorkflowEvidenceOutputSchema,
  getWorkflowOperationOutputSchema,
  getWorkflowPayloadOutputSchema,
  getWorkflowRunOutputSchema,
  getWorkflowStructureOutputSchema,
  listFrameExecutionsOutputSchema,
  listFrameExecutionsQuerySchema,
  listRunExecutionsOutputSchema,
  listRunExecutionsQuerySchema,
  listWorkflowAttemptsOutputSchema,
  listWorkflowAttemptsQuerySchema,
  listWorkflowCheckpointInventoryOutputSchema,
  listWorkflowCheckpointManifestOutputSchema,
  listWorkflowCheckpointsOutputSchema,
  listWorkflowCheckpointsQuerySchema,
  listWorkflowDescriptorsInputSchema,
  listWorkflowDescriptorsOutputSchema,
  listWorkflowEventsOutputSchema,
  listWorkflowEventsQuerySchema,
  listWorkflowEvidenceOutputSchema,
  listWorkflowEvidenceQuerySchema,
  listWorkflowFramesOutputSchema,
  listWorkflowFramesQuerySchema,
  listWorkflowOperationsOutputSchema,
  listWorkflowOperationsQuerySchema,
  listWorkflowRunsOutputSchema,
  listWorkflowRunsQuerySchema,
  listWorkflowVersionsOutputSchema,
  listWorkflowVersionsQuerySchema,
  startWorkflowInputSchema,
  startWorkflowOutputSchema,
  paginationQuerySchema,
  workflowAttemptRouteParamsSchema,
  workflowCheckpointContentQuerySchema,
  workflowCheckpointFileRouteParamsSchema,
  workflowCheckpointRouteParamsSchema,
  workflowEvidenceContentQuerySchema,
  workflowEvidenceRouteParamsSchema,
  workflowFrameRouteParamsSchema,
  workflowOperationRouteParamsSchema,
  workflowPayloadRouteParamsSchema,
  workflowRunControlOutputSchema,
  workflowRunRouteParamsSchema,
  workflowStructureQuerySchema,
} from './types.js';

/**
 * The retained workflow read and control surface.
 *
 * Every route here is part of the contract even where the shipped web client does not call it:
 * version history and per-attempt access stay available to API consumers and tests. There is no
 * per-run websocket — committed transitions reach clients on the shared runtime event bus, and a
 * client that misses one recovers through the paginated history routes.
 */
export const workflowsEndpoints = {
  descriptors: {
    id: 'workflows.descriptors',
    method: 'POST',
    path: '/workflows/descriptors',
    body: listWorkflowDescriptorsInputSchema,
    output: listWorkflowDescriptorsOutputSchema,
    errors: workflowApiErrorSchema,
  },
  start: {
    id: 'workflows.start',
    method: 'POST',
    path: '/workflows/runs',
    body: startWorkflowInputSchema,
    output: startWorkflowOutputSchema,
    errors: workflowApiErrorSchema,
  },
  listRuns: {
    id: 'workflows.listRuns',
    method: 'GET',
    path: '/workflows/runs',
    query: listWorkflowRunsQuerySchema,
    output: listWorkflowRunsOutputSchema,
    errors: workflowApiErrorSchema,
  },
  getRun: {
    id: 'workflows.getRun',
    method: 'GET',
    path: '/workflows/runs/:runId',
    params: workflowRunRouteParamsSchema,
    output: getWorkflowRunOutputSchema,
    errors: workflowApiErrorSchema,
  },
  getStructure: {
    id: 'workflows.getStructure',
    method: 'GET',
    path: '/workflows/runs/:runId/structure',
    params: workflowRunRouteParamsSchema,
    query: workflowStructureQuerySchema,
    output: getWorkflowStructureOutputSchema,
    errors: workflowApiErrorSchema,
  },
  listVersions: {
    id: 'workflows.listVersions',
    method: 'GET',
    path: '/workflows/runs/:runId/versions',
    params: workflowRunRouteParamsSchema,
    query: listWorkflowVersionsQuerySchema,
    output: listWorkflowVersionsOutputSchema,
    errors: workflowApiErrorSchema,
  },
  listFrames: {
    id: 'workflows.listFrames',
    method: 'GET',
    path: '/workflows/runs/:runId/frames',
    params: workflowRunRouteParamsSchema,
    query: listWorkflowFramesQuerySchema,
    output: listWorkflowFramesOutputSchema,
    errors: workflowApiErrorSchema,
  },
  listFrameExecutions: {
    id: 'workflows.listFrameExecutions',
    method: 'GET',
    path: '/workflows/runs/:runId/frames/:frameId/executions',
    params: workflowFrameRouteParamsSchema,
    query: listFrameExecutionsQuerySchema,
    output: listFrameExecutionsOutputSchema,
    errors: workflowApiErrorSchema,
  },
  listExecutions: {
    id: 'workflows.listExecutions',
    method: 'GET',
    path: '/workflows/runs/:runId/executions',
    params: workflowRunRouteParamsSchema,
    query: listRunExecutionsQuerySchema,
    output: listRunExecutionsOutputSchema,
    errors: workflowApiErrorSchema,
  },
  listAttempts: {
    id: 'workflows.listAttempts',
    method: 'GET',
    path: '/workflows/runs/:runId/attempts',
    params: workflowRunRouteParamsSchema,
    query: listWorkflowAttemptsQuerySchema,
    output: listWorkflowAttemptsOutputSchema,
    errors: workflowApiErrorSchema,
  },
  getAttempt: {
    id: 'workflows.getAttempt',
    method: 'GET',
    path: '/workflows/runs/:runId/attempts/:attemptId',
    params: workflowAttemptRouteParamsSchema,
    output: getWorkflowAttemptOutputSchema,
    errors: workflowApiErrorSchema,
  },
  listOperations: {
    id: 'workflows.listOperations',
    method: 'GET',
    path: '/workflows/runs/:runId/operations',
    params: workflowRunRouteParamsSchema,
    query: listWorkflowOperationsQuerySchema,
    output: listWorkflowOperationsOutputSchema,
    errors: workflowApiErrorSchema,
  },
  listEvents: {
    id: 'workflows.listEvents',
    method: 'GET',
    path: '/workflows/runs/:runId/events',
    params: workflowRunRouteParamsSchema,
    query: listWorkflowEventsQuerySchema,
    output: listWorkflowEventsOutputSchema,
    errors: workflowApiErrorSchema,
  },
  getOperation: {
    id: 'workflows.getOperation',
    method: 'GET',
    path: '/workflows/runs/:runId/operations/:operationKey',
    params: workflowOperationRouteParamsSchema,
    output: getWorkflowOperationOutputSchema,
    errors: workflowApiErrorSchema,
  },
  listEvidence: {
    id: 'workflows.listEvidence',
    method: 'GET',
    path: '/workflows/runs/:runId/evidence',
    params: workflowRunRouteParamsSchema,
    query: listWorkflowEvidenceQuerySchema,
    output: listWorkflowEvidenceOutputSchema,
    errors: workflowApiErrorSchema,
  },
  getEvidence: {
    id: 'workflows.getEvidence',
    method: 'GET',
    path: '/workflows/runs/:runId/evidence/:evidenceKey',
    params: workflowEvidenceRouteParamsSchema,
    output: getWorkflowEvidenceOutputSchema,
    errors: workflowApiErrorSchema,
  },
  listCheckpoints: {
    id: 'workflows.listCheckpoints',
    method: 'GET',
    path: '/workflows/runs/:runId/checkpoints',
    params: workflowRunRouteParamsSchema,
    query: listWorkflowCheckpointsQuerySchema,
    output: listWorkflowCheckpointsOutputSchema,
    errors: workflowApiErrorSchema,
  },
  getCheckpoint: {
    id: 'workflows.getCheckpoint',
    method: 'GET',
    path: '/workflows/runs/:runId/checkpoints/:checkpointId',
    params: workflowCheckpointRouteParamsSchema,
    output: getWorkflowCheckpointOutputSchema,
    errors: workflowApiErrorSchema,
  },
  listCheckpointInventory: {
    id: 'workflows.listCheckpointInventory',
    method: 'GET',
    path: '/workflows/runs/:runId/checkpoints/:checkpointId/inventory',
    params: workflowCheckpointRouteParamsSchema,
    query: paginationQuerySchema,
    output: listWorkflowCheckpointInventoryOutputSchema,
    errors: workflowApiErrorSchema,
  },
  listCheckpointManifest: {
    id: 'workflows.listCheckpointManifest',
    method: 'GET',
    path: '/workflows/runs/:runId/checkpoints/:checkpointId/manifest',
    params: workflowCheckpointRouteParamsSchema,
    query: paginationQuerySchema,
    output: listWorkflowCheckpointManifestOutputSchema,
    errors: workflowApiErrorSchema,
  },
  getPayload: {
    id: 'workflows.getPayload',
    method: 'GET',
    path: '/workflows/runs/:runId/payloads/:payloadRef',
    params: workflowPayloadRouteParamsSchema,
    output: getWorkflowPayloadOutputSchema,
    errors: workflowApiErrorSchema,
  },
  pause: {
    id: 'workflows.pause',
    method: 'POST',
    path: '/workflows/runs/:runId/pause',
    params: workflowRunRouteParamsSchema,
    output: workflowRunControlOutputSchema,
    errors: workflowApiErrorSchema,
  },
  resume: {
    id: 'workflows.resume',
    method: 'POST',
    path: '/workflows/runs/:runId/resume',
    params: workflowRunRouteParamsSchema,
    output: workflowRunControlOutputSchema,
    errors: workflowApiErrorSchema,
  },
  retry: {
    id: 'workflows.retry',
    method: 'POST',
    path: '/workflows/runs/:runId/retry',
    params: workflowRunRouteParamsSchema,
    output: workflowRunControlOutputSchema,
    errors: workflowApiErrorSchema,
  },
  /** Stops successors and new effects, retains every record, and reports stopping honestly. */
  cancel: {
    id: 'workflows.cancel',
    method: 'POST',
    path: '/workflows/runs/:runId/cancel',
    params: workflowRunRouteParamsSchema,
    output: workflowRunControlOutputSchema,
    errors: workflowApiErrorSchema,
  },
  /** Releases the surface attachment of a terminal run. The run stays listed and inspectable. */
  dismiss: {
    id: 'workflows.dismiss',
    method: 'POST',
    path: '/workflows/runs/:runId/dismiss',
    params: workflowRunRouteParamsSchema,
    output: workflowRunControlOutputSchema,
    errors: workflowApiErrorSchema,
  },
  advance: {
    id: 'workflows.advance',
    method: 'POST',
    path: '/workflows/runs/:runId/advance',
    params: workflowRunRouteParamsSchema,
    body: advanceWorkflowInputSchema,
    output: workflowRunControlOutputSchema,
    errors: workflowApiErrorSchema,
  },
  // `satisfies` keeps the declaration-site check that every entry is a legal endpoint — method,
  // path shape, and the schema slots — without having to restate each endpoint's generic arguments.
} as const satisfies Record<string, ApiEndpoint<any, any, any, any, any>>;

/**
 * Content routes: a sibling export, deliberately not a member of `workflowsEndpoints`.
 *
 * A content route has no `output` schema, because what it returns is a stream. Folding it into the
 * collection above would break that collection's `satisfies Record<string, ApiEndpoint>` check and
 * the typed web requester's output inference, both of which exist to catch real mistakes. Keeping
 * it beside them instead means the next non-JSON body is a declaration rather than another
 * exception.
 */
export const workflowContentEndpoints = {
  getEvidenceContent: {
    id: 'workflows.getEvidenceContent',
    method: 'GET',
    path: '/workflows/runs/:runId/evidence/:evidenceKey/content',
    params: workflowEvidenceRouteParamsSchema,
    query: workflowEvidenceContentQuerySchema,
    errors: workflowApiErrorSchema,
  },
  getCheckpointFileContent: {
    id: 'workflows.getCheckpointFileContent',
    method: 'GET',
    path: '/workflows/runs/:runId/checkpoints/:checkpointId/files/:fileId/content',
    params: workflowCheckpointFileRouteParamsSchema,
    query: workflowCheckpointContentQuerySchema,
    errors: workflowApiErrorSchema,
  },
} as const satisfies Record<string, ApiContentEndpoint<any, any, any>>;
