/**
 * The authoring contract, re-exported for runtime code.
 *
 * These are the *author's* types. The runtime almost never sees them fully applied: a bundle is
 * compiled against its own copy of the SDK, so by the time a definition reaches the loader its real
 * state, parameter and output types are gone. Structural recognition establishes the shape instead,
 * which is why the loader works in terms of the `Any…` aliases it declares rather than these.
 */
export type {
  AgentSessionHandle,
  AgentTurnEvent,
  AgentTurnTarget,
  EdgeDecision,
  GraphDefinition,
  GraphEdge,
  GraphNode,
  GraphOutcome,
  GraphStateFields,
  GraphUpdate,
  HeadlessOperationHandle,
  HeadlessOperationResult,
  NodeEvent,
  OperationContext,
  OperationNode,
  OperationResult,
  StateField,
  SubgraphNode,
  SubgraphResult,
  WaitDeclaration,
  WorkflowAgentHarness,
  WorkflowCommandManifest,
  WorkflowConversationMessage,
  WorkflowConversationPart,
  WorkflowConversationRole,
  WorkflowDefinition,
  WorkflowDestination,
  WorkflowEdgeId,
  WorkflowGraphKey,
  WorkflowInputs,
  WorkflowNodeId,
  WorkflowOrigin,
  WorkflowOutcomeId,
  WorkflowPlacementContext,
  WorkflowPlacementRequest,
  WorkflowPromptInput,
  WorkflowQuestionOption,
  WorkflowQuestionSpec,
  WorkflowSurfaceChoice,
  WorkflowSurfaceSummary,
  WorkflowUiFeedback,
  WorkflowUserInputAnswers,
  WorkflowWaitKind,
  WorkflowWorktreeChoice,
  WorkflowWorktreeSummary,
} from '@yourtechbudstudio/isagi-workflow-sdk';
