export const workbenchCopy = {
  emptyCommands: '// no commands yet',
  noCommandsRunning: '// no commands running',
  commandsLoading: '// loading commands',
  commandsConfigError: 'commands config error',
  commandsUnavailable: 'commands unavailable',
  openCommandLogsTitle: (label: string) => `Open ${label} monitor`,
  commandAuthoringTitle: 'Add commands in .isagi/config.yaml',
  commandExecutionUnavailableTitle: 'Command execution lands in the next phase',
  commandIdleDetail: 'This command has not run yet.',
  commandRemovedDetail: 'This command is no longer in .isagi/config.yaml.',
  commandRemovedSection: 'removed commands',
  commandManagedSection: 'runtime-managed commands',
  commandManagedDetail:
    'Command config needs a look, but this managed command still has live runtime state.',
  commandRemovedMarker: 'removed',
  commandOutputStreamingPending:
    'Command output is temporarily unavailable while streaming is being rebuilt.',
  commandOutputStatusCurrent: 'Command status is still current.',
  commandOutputWillStream: 'This run has PTY output ready for the streaming view.',
  commandLogConnecting: 'Connecting to command output...',
  commandLogReplaying: 'Replaying command output...',
  commandLogStreaming: 'Streaming command output.',
  commandLogFrozen: 'Command output frozen.',
  commandLogClosed: 'Command output stream closed.',
  commandLogProtocolError: 'Command output stream sent an unreadable message.',
  commandLogReadOnlyRejected: 'Command output is read-only.',
  commandLogUnavailable: 'Command output stream unavailable.',
  commandLogConnectionFailed: 'Command log stream connection failed.',
  commandLogErrorCode: (code: string) => `Stream error: ${code}`,
  commandLogExit: (exitCode: number | null, signal: string | null) =>
    signal ? `Exited by signal ${signal}.` : `Exited with code ${exitCode ?? 'unknown'}.`,
  commandRunDiagnosticDetailLabel: 'Diagnostic detail',
  commandRunDiagnostic: {
    missing_cwd: 'The configured working directory does not exist.',
    env_invalid: 'The command environment could not be prepared.',
    pty_launch_failed: 'The command could not start a PTY process.',
    runtime_stopped: 'The runtime stopped while this command was running.',
  },
  commandConfigDiagnosticTitle: 'Command config needs a look.',
  commandConfigDiagnosticBody:
    'Fix .isagi/config.yaml in this worktree, then refresh the command drawer.',
  commandReadFailedTitle: 'Commands are unavailable.',
  refreshCommands: 'Refresh',
} as const;
