import type { CommandLogStreamErrorCode } from '@isagi/contracts';

const commandLogStreamErrorSummaries: Readonly<Record<CommandLogStreamErrorCode, string>> = {
  invalid_message: 'Command output stream sent an unreadable message.',
  stream_superseded: 'Command output opened somewhere else.',
  backend_unavailable: "The command output backend isn't available.",
  backend_session_missing: 'The command output backend is gone.',
  backend_attach_failed: "Couldn't attach to command output.",
  log_read_failed: "Couldn't replay command output.",
  pty_state_load_failed: "Couldn't load command output state.",
  read_only_stream: 'Command output is read-only.',
  worktree_not_found: "Can't find that worktree. Did it get removed?",
  command_config_invalid: "Couldn't read this command's config.",
  command_not_found: "That command isn't available anymore.",
  unknown: 'Command output stream gave out.',
};

export const workbenchCopy = {
  emptyCommands: '// no commands yet',
  noCommandsRunning: '// no commands running',
  commandsLoading: '// loading commands',
  commandsConfigError: 'commands config error',
  commandsUnavailable: 'commands unavailable',
  openCommandLogsTitle: (label: string) => `Open ${label} monitor`,
  commandExecutionUnavailableTitle: 'Command execution lands in the next phase',
  commandIdleDetail: 'This command has not run yet.',
  commandRemovedDetail: 'This command is no longer in .isagi/config.yaml.',
  commandRemovedSection: 'removed commands',
  commandManagedSection: 'runtime-managed commands',
  commandManagedDetail:
    'Command config needs a look, but this managed command still has live runtime state.',
  commandRemovedMarker: 'removed',
  commandOutputNotRecorded: 'No terminal output was recorded for this run.',
  commandOutputStatusCurrent: 'Command status is still current.',
  commandOutputWillStream: 'This run has PTY output ready for the streaming view.',
  commandLogConnecting: 'Connecting to command output...',
  commandLogReplaying: 'Replaying command output...',
  commandLogStreaming: 'Streaming command output.',
  commandLogFrozen: 'Command output frozen.',
  commandLogClosed: 'Command output stream closed.',
  commandLogDropped: 'Command output stream stopped.',
  commandLogProtocolError: 'Command output stream sent an unreadable message.',
  commandLogReadOnlyRejected: 'Command output is read-only.',
  commandLogUnavailable: 'Command output stream unavailable.',
  commandLogConnectionFailed: 'Command log stream connection failed.',
  commandLogStreamError: (code: CommandLogStreamErrorCode) => commandLogStreamErrorSummaries[code],
  commandLogExit: (exitCode: number | null, signal: string | null) =>
    signal ? `Exited by signal ${signal}.` : `Exited with code ${exitCode ?? 'unknown'}.`,
  commandRunDiagnosticDetailLabel: 'Diagnostic detail',
  commandRunDiagnostic: {
    missing_cwd: 'The configured working directory does not exist.',
    env_invalid: 'The command environment could not be prepared.',
    pty_launch_failed: 'The command could not start a PTY process.',
    runtime_stopped: 'The runtime stopped while this command was running.',
  },
  commandConfigDiagnosticTitle: 'Command config needs a look.',
  commandConfigDiagnosticBody:
    'Fix .isagi/config.yaml in this worktree, then refresh the command drawer.',
  commandReadFailedTitle: 'Commands are unavailable.',
  refreshCommands: 'Refresh',
} as const;
